# Generated by Django 5.0.4 on 2024-04-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailModel',
        ),
    ]
