# Generated by Django 5.0.4 on 2024-04-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailModel',
            new_name='Reg',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='cpas',
            new_name='cp',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='fname',
            new_name='fn',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='gender',
            new_name='g',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='lname',
            new_name='ln',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='pas',
            new_name='p',
        ),
    ]
